from src.extraction.marker_run import run_marker
from src.extraction.parser import extract_transactions # Your new Regex function
from src.extraction.validator import validate_statement
import os

# Paths
PDF_PATH = "data/raw/statement.pdf"
MD_FOLDER = "data/interim"
CSV_PATH = "data/processed/statement_cleaned.csv"

def main():
    # Step 1: PDF -> Markdown (AI Layout Analysis)
    if run_marker(PDF_PATH, MD_FOLDER):
        
        # Get the .md file generated by Marker
        md_files = [f for f in os.listdir(MD_FOLDER) if f.endswith('.md')]
        if not md_files:
            print("Error: Marker did not produce a markdown file.")
            return
        
        full_md_path = os.path.join(MD_FOLDER, md_files[0])
        
        # Read the markdown text
        with open(full_md_path, "r", encoding="utf-8") as f:
            md_text = f.read()

        # Step 2: Markdown -> CSV (Regex Logic - High Accuracy)
        if extract_transactions(md_text, CSV_PATH):
            
            # Step 3: Validate the Math
            validate_statement(CSV_PATH)

if __name__ == "__main__":
    main()
